preload = /home/maxi/.config/hypr/wallpapers/wallhaven-9dmmr1_1920x1200.png

wallpaper {
    monitor = eDP-1
    path = /home/maxi/.config/hypr/wallpapers/wallhaven-9dmmr1_1920x1200.png
}

splash = false
